M48
; DRILL file {KiCad 8.0.0} date 2025-03-28T23:26:53+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-28T23:26:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.1181
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.1909
%
G90
G05
T1
X4.963Y-4.633
T2
X4.624Y-5.428
M30
